### ISSUE TITLE
Custom op codes cause issues for B::Deparse

### ISSUE THREAD

**Issue by tobyink** [p5pclub/ref-util-xs#2]
The following illustrates what I mean:

```
perl -MRef::Util::XS=is_ref -MO=Deparse -e'is_ref[]'
```

VPIT's Sub::Op shows a workaround for this. Whether that's a wise way of solving the problem, I'll leave up to you to decide.

**Comment by xsawyerx** [comment]
Fixed by @haarg in #3. Released in 0.117 just now.
